# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5986fe1c0087648dd13eedb8aa7616d0"
name = "my-first-app"
handle = "my-first-app-1708"
application_url = "https://top-soap-gabriel-supporting.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://top-soap-gabriel-supporting.trycloudflare.com/auth/callback",
  "https://top-soap-gabriel-supporting.trycloudflare.com/auth/shopify/callback",
  "https://top-soap-gabriel-supporting.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
